language: generic
sudo: required
service:
  - docker

before_install:
  - docker build -t icaromagnago/docker-react-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true icaromagnago/docker-react-ci npm run test