language: generic
sudo: required
service:
  - docker

before_install:
  - docker build -t icaromagnago/docker-react-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true icaromagnago/docker-react-ci npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: docker-react-ci
  env: "DockerReactCi-env"
  bucket_name: "elasticbeanstalk-sa-east-1-531401195884"
  bucket_path: "docker-react-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY